(#21568): Adding java necessary '--add-opens' options to permit unsafe access for xstream reflection
dotCMS/tomcat pull request #22
Opened 2022-02-18 22:55 UTC by victoralfaro-dotcms

2022-02-24 16:31 UTC, dsilvam approved these changes

2022-03-01 13:15 UTC, freddyucv approved these changes

2022-03-01 13:17 UTC, wezell requested changes
This does not seem like the right solution for us.  First, we were supposed to be removing Xstream as it has a number of critical vulnerabilities and replacing the xml with json.  How did we get from that ask to basically exposing the entire java package structure to XStream?

2022-03-01 17:25 UTC, victoralfaro-dotcms commented
@wezell closing this PR as you are right.

2022-03-01 17:25 UTC, closed without merging